"""Templates for ``qpython new``.

Generated projects ship an ``application.yaml`` (YAML is the documented
default format) and a runnable entry point. The scaffold never installs
anything: it prints the commands, leaving virtualenv creation to the user.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

Flavor = Literal["fastapi", "grpc", "hybrid"]

_APPLICATION_YAML = """app:
  name: {name}
  env: development
  debug: true

server:
  http:
    host: "127.0.0.1"
    port: 8000
  grpc:
    host: "127.0.0.1"
    port: 50051

logger:
  level: INFO
  format: json

trace:
  enabled: false

jwt:
  enabled: false
"""

_FASTAPI_MAIN = '''"""{name} -- a FastAPI service built on PythonForge."""

from pathlib import Path

import uvicorn
from fastapi import APIRouter

from pythonforge.config import load_config
from pythonforge.context import RequestContext
from pythonforge.transport.http import create_app

router = APIRouter()


@router.get("/api/v1/hello")
async def hello() -> dict[str, str | None]:
    return {{"message": "Hello from {name}", "request_id": RequestContext().request_id}}


config = load_config(config_dir=Path(__file__).parent)
app = create_app(config, routers=[router])

if __name__ == "__main__":
    uvicorn.run(app, host=config.server.http.host, port=config.server.http.port)
'''

_GRPC_MAIN = '''"""{name} -- a gRPC service built on PythonForge.

Replace the example servicer with your own generated stubs; see
scripts/gen_protos.sh in the PythonForge repository for the generation
workflow (grpcio-tools is a development dependency only).
"""

import asyncio
from pathlib import Path

from pythonforge.config import load_config
from pythonforge.transport import ServiceRuntime
from pythonforge.transport.grpc import create_grpc_server
from pythonforge.transport.grpc.generated.pythonforge.example.v1 import (
    example_pb2 as pb,
)
from pythonforge.transport.grpc.generated.pythonforge.example.v1 import (
    example_pb2_grpc as pbg,
)


class ExampleService(pbg.ExampleServiceServicer):
    async def Echo(self, request, context):  # noqa: N802
        return pb.EchoResponse(message=request.message)


async def main() -> None:
    config = load_config(config_dir=Path(__file__).parent)
    server = create_grpc_server(config.server.grpc)
    pbg.add_ExampleServiceServicer_to_server(ExampleService(), server)

    runtime = ServiceRuntime(config)
    runtime.add_grpc_server(server)
    await runtime.serve_forever()


if __name__ == "__main__":
    asyncio.run(main())
'''

_HYBRID_MAIN = '''"""{name} -- FastAPI and gRPC in one process, via ServiceRuntime."""

import asyncio
from pathlib import Path

import uvicorn
from fastapi import APIRouter

from pythonforge.config import load_config
from pythonforge.context import RequestContext
from pythonforge.transport import ServiceRuntime
from pythonforge.transport.grpc import create_grpc_server
from pythonforge.transport.grpc.generated.pythonforge.example.v1 import (
    example_pb2 as pb,
)
from pythonforge.transport.grpc.generated.pythonforge.example.v1 import (
    example_pb2_grpc as pbg,
)
from pythonforge.transport.http import create_app

router = APIRouter()


@router.get("/api/v1/hello")
async def hello() -> dict[str, str | None]:
    return {{"message": "Hello from {name}", "request_id": RequestContext().request_id}}


class ExampleService(pbg.ExampleServiceServicer):
    async def Echo(self, request, context):  # noqa: N802
        return pb.EchoResponse(message=request.message)


async def main() -> None:
    config = load_config(config_dir=Path(__file__).parent)

    app = create_app(config, routers=[router])
    http_server = uvicorn.Server(
        uvicorn.Config(
            app, host=config.server.http.host, port=config.server.http.port, log_config=None
        )
    )

    grpc_server = create_grpc_server(config.server.grpc)
    pbg.add_ExampleServiceServicer_to_server(ExampleService(), grpc_server)

    # Both transports start atomically; if either fails, the other is torn down.
    runtime = ServiceRuntime(config)
    runtime.add_uvicorn_server(http_server)
    runtime.add_grpc_server(grpc_server)
    await runtime.serve_forever()


if __name__ == "__main__":
    asyncio.run(main())
'''

_README = """# {name}

Generated by `qpython new {flavor}`.

## Run

```bash
python3 -m venv .venv
source .venv/bin/activate
python -m pip install --upgrade pip
python -m pip install {install_target}
python main.py
```

Configuration lives in `application.yaml`. Every value can be overridden by
an environment variable, e.g. `PYTHONFORGE_SERVER__HTTP__PORT=9000`.
"""

_MAINS: dict[str, str] = {
    "fastapi": _FASTAPI_MAIN,
    "grpc": _GRPC_MAIN,
    "hybrid": _HYBRID_MAIN,
}

_INSTALL_TARGETS: dict[str, str] = {
    "fastapi": '"pythonforge"',
    "grpc": '"pythonforge[grpc]"',
    "hybrid": '"pythonforge[grpc]"',
}


def scaffold(destination: Path, name: str, flavor: Flavor) -> list[Path]:
    """Write a runnable project skeleton; returns the files created."""
    destination.mkdir(parents=True, exist_ok=True)

    files = {
        destination / "application.yaml": _APPLICATION_YAML.format(name=name),
        destination / "main.py": _MAINS[flavor].format(name=name),
        destination / "README.md": _README.format(
            name=name, flavor=flavor, install_target=_INSTALL_TARGETS[flavor]
        ),
    }
    for path, content in files.items():
        path.write_text(content)
    return list(files)
